name: Buildx latest
on:
  push:
    branches: [master]
    paths-ignore:
      - .devcontainer
      - .github/workflows/buildx-pr.yml
      - .github/workflows/buildx-release.yml
      - .github/workflows/dockerhub-description.yml
      - .github/workflows/labels.yml
      - .vscode
      - .gitignore
      - docker-compose.yml
      - LICENSE
      - README.md
      - title.svg
  schedule:
    - cron: '0 9 * * 0'
jobs:
  alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Buildx setup
        uses: crazy-max/ghaction-docker-buildx@v1
      - name: Dockerhub login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u qmcgaw --password-stdin 2>&1
      - name: Buildx
        run: |
          docker buildx build \
            -f alpine.Dockerfile \
            --progress plain \
            --platform=linux/amd64 \
            --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
            --build-arg VCS_REF=`git rev-parse --short HEAD` \
            --build-arg VERSION=alpine \
            -t qmcgaw/basedevcontainer:latest \
            -t qmcgaw/basedevcontainer:alpine \
            --push \
            .
      - run: curl -X POST https://hooks.microbadger.com/images/qmcgaw/basedevcontainer/bEP2lBLpFjot59Gyxz4SuMvtj4M= || exit 0

  debian-10:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Buildx setup
        uses: crazy-max/ghaction-docker-buildx@v1
      - name: Dockerhub login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u qmcgaw --password-stdin 2>&1
      - name: Buildx
        run: |
          docker buildx build \
            -f debian.Dockerfile \
            --build-arg DEBIAN_VERSION=buster-slim \
            --progress plain \
            --platform=linux/amd64 \
            --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
            --build-arg VCS_REF=`git rev-parse --short HEAD` \
            --build-arg VERSION=debian \
            -t qmcgaw/basedevcontainer:debian \
            --push \
            .
